# Create Heatmaps for Weather Parameters

In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Zhigansk,RU,2021-11-15 02:06:42,66.7697,123.3711,-23.55,99,70,7.36
1,1,Atar,MR,2021-11-15 02:06:42,20.5169,-13.0499,79.09,33,40,3.20
2,2,Lewiston,US,2021-11-15 02:05:43,44.1003,-70.2148,44.22,85,90,0.00
3,3,Yellowknife,CA,2021-11-15 02:02:00,62.4560,-114.3525,17.29,92,76,5.99
4,4,Toktogul,KG,2021-11-15 02:06:43,41.8708,72.9402,38.01,98,95,1.19

In [3]:
# Get the data types
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Humidity"]

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()
                            
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
                            
# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [7]:
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Humidity"]
max_temp = temperatures.max()

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()
                            
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
                            
# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
#Create a Maximum Temperature Heatmap

In [9]:
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Humidity"]
max_temp = temperatures.max()

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
                            
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in temperatures])

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
                            
# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# 1. Assign the locations to an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]

# 2. Assign the weights variable to some values.
temperatures = city_data_df["Humidity"]
max_temp = temperatures.max()

# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
                            
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in temperatures], dissipating=False, max_intensity=300, point_radius=4)

# 5. Add the heatmap layer.
fig.add_layer(heatmap_layer)
                            
# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of Percent Cloudiness Heatmap
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of Wind Speed Heatmap
locations = city_data_df[["Lat", "Lng"]]
winds = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=winds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [15]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Atar,MR,2021-11-15 02:06:42,20.5169,-13.0499,79.09,33,40,3.20
7,7,Ambon,ID,2021-11-15 02:06:44,-3.6954,128.1814,82.45,73,89,1.72
9,9,Frontera,MX,2021-11-15 02:06:45,26.9333,-101.4500,75.33,27,0,3.00
10,10,Carnarvon,AU,2021-11-15 02:06:46,-24.8667,113.6333,75.60,52,1,8.23
12,12,Vaini,TO,2021-11-15 02:06:47,-21.2000,-175.2000,80.76,78,20,11.50
14,14,Kavieng,PG,2021-11-15 02:06:47,-2.5744,150.7967,84.97,69,70,10.18
21,21,Sibolga,ID,2021-11-15 02:06:50,1.7427,98.7792,82.45,67,99,0.87
31,31,Kapaa,US,2021-11-15 02:06:55,22.0752,-159.3190,78.12,73,20,6.91
32,32,Kendari,ID,2021-11-15 02:06:55,-3.9450,122.4989,84.38,68,100,3.11
36,36,Payakumbuh,ID,2021-11-15 02:06:58,-0.2202,100.6308,77.56,64,100,1.90

In [16]:
preferred_cities_df.count()

City_ID       146
City          146
Country       145
Date          146
Lat           146
Lng           146
Max Temp      146
Humidity      146
Cloudiness    146
Wind Speed    146
dtype: int64

In [17]:
preferred_cities_df.isnull().sum()

City_ID       0
City          0
Country       1
Date          0
Lat           0
Lng           0
Max Temp      0
Humidity      0
Cloudiness    0
Wind Speed    0
dtype: int64

In [18]:
preferred_cities_df.notnull().sum()

City_ID       146
City          146
Country       145
Date          146
Lat           146
Lng           146
Max Temp      146
Humidity      146
Cloudiness    146
Wind Speed    146
dtype: int64

In [ ]:
#Consider the following guidance:

#Depending on the time of year and the seasons, you might have to adjust the minimum and maximum temperature to get enough cities.
#It is a good idea to keep the number of cities to fewer than 200 to make it easier to plot the markers on the heatmap.
#If you have some rows with null values, you'll need to drop them using the dropna() method at the end of your filtering statement when you are creating the new DataFrame.

In [20]:
preferred_cities_df.dropna()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Atar,MR,2021-11-15 02:06:42,20.5169,-13.0499,79.09,33,40,3.20
7,7,Ambon,ID,2021-11-15 02:06:44,-3.6954,128.1814,82.45,73,89,1.72
9,9,Frontera,MX,2021-11-15 02:06:45,26.9333,-101.4500,75.33,27,0,3.00
10,10,Carnarvon,AU,2021-11-15 02:06:46,-24.8667,113.6333,75.60,52,1,8.23
12,12,Vaini,TO,2021-11-15 02:06:47,-21.2000,-175.2000,80.76,78,20,11.50
...,...,...,...,...,...,...,...,...,...,...
577,577,Kalmunai,LK,2021-11-15 02:10:53,7.4167,81.8167,79.81,80,27,2.82
580,580,Acajutla,SV,2021-11-15 02:10:54,13.5928,-89.8275,79.66,74,42,6.76
585,585,Dourbali,TD,2021-11-15 02:10:56,11.8091,15.8632,79.43,16,19,8.84
589,589,Muli,MV,2021-11-15 02:10:57,2.9167,73.5667,82.81,71,6,17.81
592,592,Alibag,IN,2021-11-15 02:10:59,18.6411,72.8792,82.47,73,100,5.08

In [21]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

          City Country  Max Temp      Lat       Lng Hotel Name
1         Atar      MR     79.09  20.5169  -13.0499
7        Ambon      ID     82.45  -3.6954  128.1814
9     Frontera      MX     75.33  26.9333 -101.4500
10   Carnarvon      AU     75.60 -24.8667  113.6333
12       Vaini      TO     80.76 -21.2000 -175.2000
14     Kavieng      PG     84.97  -2.5744  150.7967
21     Sibolga      ID     82.45   1.7427   98.7792
31       Kapaa      US     78.12  22.0752 -159.3190
32     Kendari      ID     84.38  -3.9450  122.4989
36  Payakumbuh      ID     77.56  -0.2202  100.6308

In [22]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [23]:
# Dependencies and Setup
import requests
import gmaps

# Import API key
from config import g_key

In [24]:
# Set the parameters to search for a hotel in Paris.
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key,
    "location": "48.8566, 2.3522"}
# Use base URL to search for hotels in Paris.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()

hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uECrNuCY84_sp_cZ0JiNp38-aB6ZruD08_wC7hT6NJsSLOWOLzTOlQXcXHaxW9vhHYPeNHa5d_5R4NiO3iWTqbs8ZhwNKc6LsD7iZAl16zC9pzrxvJQAyFY0INibBKQDj6B_yz5EcuTp8t4faEsDgFh6_2X4nt8ptVwhCEvKXcfeNizuRpCSiHT1t2m2VJFC1UWNtl8sP18XsqgbdGyC_pIzD5NJp_tzwDaqEXZMewYLkYpEwuot7_HdR9rilZ6NscfFnwsDGnhwAXE094yFv0TUbvTLQsiYKEe4NKSGV3k8ye96xz1NMob0P-puFLSI0jLmwrH3GbOHKI8dt3yuEzIQh30qnpw_tP4LaRr45dNLlffMPy82-v0kahn3189Xrxi4vlJxUrX5bZixiKS8E7LDD5NWgfN8fK4h0blu_lUtfDSVdwKqbJfl',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8581126, 'lng': 2.3529277},
    'viewport': {'northeast': {'lat': 48.8594360302915,
      'lng': 2.354355480291502},
     'southwest': {'lat': 48.8567380697085, 'lng': 2.351657519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Duo',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3840,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107554201425443337224">Hôtel Duo</a>'],
     'photo_reference': 'Aap_uEBkQskvG6BnHN0vqtxPFCjUkO8Z0xUDAhw8gc8TU21oF5kwVYqy7L_N_Pa9j_fNEHk1CEWdu_sxPrhEFXezMsxAiEst-ai1uT3v0FMjIpZEcX-sqKHHUaMsl8xqKU_UQ90epwqz66K3fOuuJ6Ao5mtOpF-Wk1SiY4vR5HC767HDWUN1',
     'width': 5760}],
   'place_id': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'plus_code': {'compound_code': 'V953+65 Paris, France',
    'global_code': '8FW4V953+65'},
   'rating': 4.2,
   'reference': 'ChIJWU9CqB1u5kcR5P1F2SMoJmc',
   'scope': 'GOOGLE',
   'types': ['night_club',
    'spa',
    'lodging',
    'bar',
    'gym',
    'health',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 308,
   'vicinity': '11 Rue du Temple, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8582861, 'lng': 2.3464944},
    'viewport': {'northeast': {'lat': 48.85954748029151,
      'lng': 2.347782830291502},
     'southwest': {'lat': 48.85684951970851, 'lng': 2.345084869708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Britannique - Paris Centre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108984000175492464929">Hôtel Britannique - Paris Centre</a>'],
     'photo_reference': 'Aap_uEBALOVkhfX-lZUnjZ6l7M_BbPu8kCvv9PygmgqjGfLqOWewmcOxguh_zLzltSjwSypldf4BHOXS26NJVydYdAWzufqocFfzPX4ovt9jUBASnExPHKibmbCXN0qeW_5aKJ6j6zZPce3-ZCN4nNzW4QYlmKk-CRNLimDDgNcRf2qozezW',
     'width': 1476}],
   'place_id': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'plus_code': {'compound_code': 'V85W+8H Paris, France',
    'global_code': '8FW4V85W+8H'},
   'rating': 4.6,
   'reference': 'ChIJ-4Siox9u5kcRm9vM6DcMXyU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 638,
   'vicinity': '20 Avenue Victoria, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8606655, 'lng': 2.3469293},
    'viewport': {'northeast': {'lat': 48.8617653302915,
      'lng': 2.348020880291502},
     'southwest': {'lat': 48.85906736970851, 'lng': 2.345322919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Les Halles Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 849,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102565262508115704337">Citadines Les Halles Paris (Apart hotel Paris)</a>'],
     'photo_reference': 'Aap_uEB6_WnDmusA72YiLHj1nxhX_2_C59mbAhw51KhOjnBzpmhGKRZOTN5jlG_oHE2kWvpxf7ymrboChpv5zO6HLVyqyHhMx5GqFCAgtP3s3FNpDtlVCGqfr4lZvLIcEQ7R5r4NxoY5weOcVlnl937GgBnindet_QlKhkIdO3xeK5Hdy_rt',
     'width': 1280}],
   'place_id': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'plus_code': {'compound_code': 'V86W+7Q Paris, France',
    'global_code': '8FW4V86W+7Q'},
   'rating': 4.1,
   'reference': 'ChIJQ_QDrxhu5kcRJzNxLLEOSfU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 866,
   'vicinity': '4 Rue des Innocents, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8607658, 'lng': 2.3465318},
    'viewport': {'northeast': {'lat': 48.8620584302915,
      'lng': 2.347692880291501},
     'southwest': {'lat': 48.85936046970851, 'lng': 2.344994919708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Novotel Paris Les Halles',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111815616573299411056">Novotel Paris Les Halles</a>'],
     'photo_reference': 'Aap_uEBhMcXmqZGQIQRxKUDlm9onsnSYXn9mHns_PsHSAd44kWaq5sQa-Dqb8HEyQliW-yKkgUb8t3jCA80TVsI9vlnK3kF9LS8hs8eMQOGeawIWzFKAzJnlmbrJlZ2Lyyeyzdp0-9AGunCoyZaB05_7pC90wK2HlX0qDqusTt1rsx44_k7U',
     'width': 3000}],
   'place_id': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'plus_code': {'compound_code': 'V86W+8J Paris, France',
    'global_code': '8FW4V86W+8J'},
   'rating': 4.4,
   'reference': 'ChIJGW2pNx9u5kcRI3oyL8NG5BQ',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 2270,
   'vicinity': '8 Place Marguerite de Navarre, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.860352, 'lng': 2.3440948},
    'viewport': {'northeast': {'lat': 48.86165553029149,
      'lng': 2.345549080291502},
     'southwest': {'lat': 48.8589575697085, 'lng': 2.342851119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Ducs de Bourgogne',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1390,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101411638353598558320">Hôtel Ducs de Bourgogne</a>'],
     'photo_reference': 'Aap_uECwPQRrm9bS93eUQOshQv7j0P-7FQ6RDE-sfS5HEMMjAMSnUjx3zCh-qUNuKCz48hJM8CfxNZN-on_VR6HS2CkhgRBWYu5tbjk4810npoBzehxpyGDPQ7jf8u8M4R-Cil9KKOvv9gtwbF8-6urCnKz13WzgYhE2g2TkE95dK2H3fDDz',
     'width': 2048}],
   'place_id': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'plus_code': {'compound_code': 'V86V+4J Paris, France',
    'global_code': '8FW4V86V+4J'},
   'rating': 4.5,
   'reference': 'ChIJifTG5yFu5kcRdnisbwxnAx4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 279,
   'vicinity': '19 Rue du Pont Neuf, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8555091, 'lng': 2.3408736},
    'viewport': {'northeast': {'lat': 48.8569076302915,
      'lng': 2.342319280291502},
     'southwest': {'lat': 48.8542096697085, 'lng': 2.339621319708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Citadines Saint-Germain-des-Prés Paris (Apart hotel Paris)',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113188832595116816387">Citadines Saint-Germain-des-Prés Paris</a>'],
     'photo_reference': 'Aap_uEBSs05bpByDqlqgPOd9NeUxWHFHxPyegQau2m4Sa7XdjRfHYuSymknmc5aFh_RrXFvT8UIs5ra5EFApiA3DuGOvPYyOW4c6Wh_vO-VddWbRqYyeg2tmoq6hoxgx0UkNwomRx1miz84C_Bt8QHWVHLs4VXYSEuG1KqLylhnpONGFKDhn',
     'width': 6720}],
   'place_id': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'plus_code': {'compound_code': 'V84R+68 Paris, France',
    'global_code': '8FW4V84R+68'},
   'rating': 4.3,
   'reference': 'ChIJo5pYcN9x5kcRERXdocMgqmE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 714,
   'vicinity': '53 ter Quai des Grands Augustins, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8663519, 'lng': 2.3606461},
    'viewport': {'northeast': {'lat': 48.86775308029149,
      'lng': 2.361905130291502},
     'southwest': {'lat': 48.8650551197085, 'lng': 2.359207169708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Paris France Hôtel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2673,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102332962500946068613">Paris France Hôtel</a>'],
     'photo_reference': 'Aap_uEDG7RUi7JzkzR2ZN3LgptMU8YYxWpjIt_3L3OJg0xFFLCTAlNO8g53M4u063L0J06CyljJ_y779t5MvtyxVkK9b4gcZehvChpMiKxvjEez28-7IPI_AsgZSZnnKyL-paJj3w2ftgAnulfli3dvO5qvREN6SlHB0bGKzYKn7y6UnoO0C',
     'width': 3463}],
   'place_id': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'plus_code': {'compound_code': 'V986+G7 Paris, France',
    'global_code': '8FW4V986+G7'},
   'rating': 4.3,
   'reference': 'ChIJhXWLZg9u5kcRDVyqoZYgcmg',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 393,
   'vicinity': '72 Rue de Turbigo, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.86386539999999, 'lng': 2.3325488},
    'viewport': {'northeast': {'lat': 48.8650759802915,
      'lng': 2.333775730291502},
     'southwest': {'lat': 48.8623780197085, 'lng': 2.331077769708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Regina Louvre',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 3700,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109908333790946649027">Hôtel Regina Louvre</a>'],
     'photo_reference': 'Aap_uEBOEX6tMQ5D5OASn8eI8BKnJt8zzWiST6g5zguxslpNVuVhffjf09IwyyWrfeG1ffZbyb0LZ-SuViRP7VtI2YFHTm6yUZFt82pGxuX6j8nmVsXCMs8wfD9VkmSGn0j8-QOyHOimhDfvx67VkKLWC-OWa51pgrRemC6rVgEYnDOLgtvp',
     'width': 5550}],
   'place_id': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'plus_code': {'compound_code': 'V87M+G2 Paris, France',
    'global_code': '8FW4V87M+G2'},
   'rating': 4.4,
   'reference': 'ChIJP_-HCS9u5kcRsj9b1x7Pl8w',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 508,
   'vicinity': '2 Place des Pyramides, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84795229999999, 'lng': 2.370869},
    'viewport': {'northeast': {'lat': 48.8492035302915,
      'lng': 2.372290080291501},
     'southwest': {'lat': 48.8465055697085, 'lng': 2.369592119708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'ibis Paris Gare de Lyon Ledru Rollin 12ème',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2048,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101181280085797863615">Kevin Nguyen</a>'],
     'photo_reference': 'Aap_uECuh9ZOqTVBPtfjKLQmKu2OC_Mh0q7P54ESVsXrA507hKP7J2k3xa-RtiSqBeq2QRfsGTMt7c7cPDPfRTodsBeVRAXnYR3DWYor2kAXFZoc4E5ffPgZx-G_S_S-PuWe0xZeFdRDc-6WOuSxfqr0F75FIIImzkp5TeQ0P8wKN9_BK82S',
     'width': 1536}],
   'place_id': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'plus_code': {'compound_code': 'R9XC+58 Paris, France',
    'global_code': '8FW4R9XC+58'},
   'rating': 4.1,
   'reference': 'ChIJ9RNxcQNy5kcRnZJ4vsuXcow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 841,
   'vicinity': '41/43 Avenue Ledru Rollin, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8710647, 'lng': 2.34991},
    'viewport': {'northeast': {'lat': 48.87241888029151,
      'lng': 2.351188530291502},
     'southwest': {'lat': 48.86972091970851, 'lng': 2.348490569708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel des Comédies Paris',
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114696623290303183213">Noble</a>'],
     'photo_reference': 'Aap_uEAKReBw_C-kPRbfInwtlrpTMNt31q55JJZKWd_5ERUCBBWW7i4vT4JSyEsLUm4pGV8MFjV4qx4sN4aY5LZ9mj8DZhWIHvQq6XSpKDxc1u3pSAgHsm2h7FDvoBwDlJMPFILd0PrWVtKRo_wMOlvTVFkcX19bp1gBjUsREFVyc7vZ5hyp',
     'width': 3000}],
   'place_id': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'plus_code': {'compound_code': 'V8CX+CX Paris, France',
    'global_code': '8FW4V8CX+CX'},
   'rating': 4.3,
   'reference': 'ChIJn6ginxZu5kcRmAEK0OHm0cI',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 196,
   'vicinity': "8 Rue d'Hauteville, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.84754640000001, 'lng': 2.3718722},
    'viewport': {'northeast': {'lat': 48.8488750302915,
      'lng': 2.373125480291502},
     'southwest': {'lat': 48.8461770697085, 'lng': 2.370427519708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel De France Gare de Lyon Bastille',
   'photos': [{'height': 787,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117462031751048846575">Hôtel De France Gare de Lyon Bastille</a>'],
     'photo_reference': 'Aap_uEASmm07XkO5ndgK9NaTCEwnUP6YtVngkqxoiovN3U9raewRXNJ4VgE_nspMe-j9qw5IRSINoq5qazKlSa3d8D52PfsRFdRXEnMvGDKnrH205XFU1XELXVwr7M7OceJXQfpRDGlboMhL7CmeVNY8Bthq8T7lSoBz_Sas5dwppkvokeOo',
     'width': 1181}],
   'place_id': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'plus_code': {'compound_code': 'R9XC+2P Paris, France',
    'global_code': '8FW4R9XC+2P'},
   'rating': 3.3,
   'reference': 'ChIJz6DBYgNy5kcRhOu1LhDIECM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 382,
   'vicinity': '12 Rue de Lyon, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8717386, 'lng': 2.3447052},
    'viewport': {'northeast': {'lat': 48.8731374802915,
      'lng': 2.346059980291502},
     'southwest': {'lat': 48.8704395197085, 'lng': 2.343362019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Prélude Opéra Paris',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 5120,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113098608949799179620">Chrystelle Baudry</a>'],
     'photo_reference': 'Aap_uEAjrX8ieP7oPifTE8a5iXYjxCZ8vueRR4Krf17UZqcv2Th6q9GsasqN0Nrr1D6T1KgN-tgBxy0NrNBLJNGkyRArFVrTazghEG_TSlvoBkl7Bj-UwD4e0r6IuXnF-fFyJHqlwXXBS933qhTUyedX_5Arv0TRXCb3VJrato2L8e1pg6Jd',
     'width': 3840}],
   'place_id': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'plus_code': {'compound_code': 'V8CV+MV Paris, France',
    'global_code': '8FW4V8CV+MV'},
   'rating': 4.2,
   'reference': 'ChIJ8e3Qcj5u5kcR2MIGwNxustk',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 384,
   'vicinity': '8 Cité Bergère, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8423434, 'lng': 2.3632087},
    'viewport': {'northeast': {'lat': 48.8436624802915,
      'lng': 2.364700930291502},
     'southwest': {'lat': 48.8409645197085, 'lng': 2.362002969708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Libertel Austerlitz Jardin des Plantes',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4480,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/114802271282641766772">Hôtel Libertel Austerlitz Jardin des Plantes</a>'],
     'photo_reference': 'Aap_uEBa1CeB892zliCGUVRSvWH4o5-iN0aLXqpOV8wR1eMjwRiMyVBd9IJzW6gO28zC9hfR4VnKY6b8xiOFMNcyEhyWMhHBVFQCRDHiqsB130qk8oV8B2klTB-3xHEU8C8e035Wv-a5aDkDksuuksIgiu1mhFbjsaMsfGV53iH7to9NQPFg',
     'width': 6720}],
   'place_id': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'plus_code': {'compound_code': 'R9R7+W7 Paris, France',
    'global_code': '8FW4R9R7+W7'},
   'rating': 4,
   'reference': 'ChIJe-udXPZx5kcRKURHNFv5BSw',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 448,
   'vicinity': "12 Boulevard de l'Hôpital, Paris"},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.8642974, 'lng': 2.3308142},
    'viewport': {'northeast': {'lat': 48.8655789302915,
      'lng': 2.332153980291502},
     'southwest': {'lat': 48.8628809697085, 'lng': 2.329456019708498}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Saint James Albany Paris Hôtel Spa',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 400,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108570400659068256718">Saint James Albany Paris Hôtel Spa</a>'],
     'photo_reference': 'Aap_uEDu_KY-2DZkdFcmOiVPntRbT_1ITq7zQ-K9WcZD9UyiEs04DvoX310Gi-12y5tM_nFjaLZJz6e9YtT_udcv3YkHyQRhHmC2y8-QH9-2swIZj1ty6e47KBqDySWY53IUi81ul0maDKGUpVlgZv1PHFiQ0pyzPOiFfQx16BkBQzzJoker',
     'width': 600}],
   'place_id': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'plus_code': {'compound_code': 'V87J+P8 Paris, France',
    'global_code': '8FW4V87J+P8'},
   'rating': 4,
   'reference': 'ChIJ8znTVS5u5kcREq8TmzOICFs',
   'scope': 'GOOGLE',
   'types': ['lodging',
    'bar',
    'restaurant',
    'food',
    'point_of_interest',
    'establishment'],
   'user_ratings_total': 1075,
   'vicinity': '202 Rue de Rivoli, Paris'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 48.87110329999999, 'lng': 2.3389728},
    'viewport': {'northeast': {'lat': 48.8724588802915,
      'lng': 2.340112930291502},
     'southwest': {'lat': 48.8697609197085, 'lng': 2.337414969708499}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hôtel Icône',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1066,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108137830440312077288">Hôtel Icône</a>'],

In [25]:
len(hotels["results"])

20

In [28]:
hotels["results"][0]["name"]

'Hôtel Duo'

In [31]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [32]:
hotel_df.head()

         City Country  Max Temp      Lat       Lng             Hotel Name
1        Atar      MR     79.09  20.5169  -13.0499         Oumou Elghoura
7       Ambon      ID     82.45  -3.6954  128.1814   Swiss-Belhotel Ambon
9    Frontera      MX     75.33  26.9333 -101.4500       Casagrande Hotel
10  Carnarvon      AU     75.60 -24.8667  113.6333  Hospitality Carnarvon
12      Vaini      TO     80.76 -21.2000 -175.2000    Keleti Beach Resort

In [33]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [34]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [35]:
#First, the info_box_template variable is assigned to a multiline string using three quotes. The text inside the multiline string is HTML code. 
#HTML code is defined by the opening and closing the angular brackets (e.g., <tag> and <tag/>). 
#Angular brackets always come in pairs. The opening angular bracket is followed by some text inside, such as dl, dt, and dd. 
#The closing angular bracket is preceded by a forward-slash ("/"). The text inside with the angular brackets is called a tag. 
#We'll see more examples of HTML code in an upcoming module.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [36]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))